### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by soleribbon** [yousefissa/Adidas-Sitekey#1]
(in Adidas-Sitekey folder) 
python3 sitekey_only.py

File "sitekey_only.py", line 16, in <module>
    get_sitekey()
  File "sitekey_only.py", line 11, in get_sitekey
    sitekey = soup.find('div', attrs={'class': 'g-recaptcha'})['data-sitekey']
TypeError: 'NoneType' object is not subscriptable

????????

**Comment by yousefissa** [comment]
It means that no site key was found on a link. I added error handling for that problem, so it'll tell you that it's wrong. I'm working on an update that will look for links itself so you won't get that error anymore.

**Comment by soleribbon** [comment]
Thanks!!
