### ISSUE TITLE
Maybe I something wrong??

### ISSUE THREAD

**Issue by cornxhof** [yousefissa/Adidas-Sitekey#3]
Hello,
I get this error.

Can you help me?? Do I something wrong?

Corny$ cd desktop
Corn-MacBook-Pro:desktop Corny$ cd adidas-sitekey-master
Corn-MacBook-Pro:adidas-sitekey-master Corny$ python3 sitekey_only.py
Traceback (most recent call last):
  File "sitekey_only.py", line 2, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

Thanks for the help!!

**Comment by yousefissa** [comment]
Install the bs4 module.
